# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

1.24.3


#### 3. Create a null vector of size 10 (★☆☆)

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [25]:
A = np.zeros(15)
print(A.size)
print(A.itemsize)
print(A.itemsize*A.size)
print(A.nbytes)
# answer(4)

15
8
120
120


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
hint(5)
answer(5)
!python -c "import numpy; numpy.info(numpy.add)"

hint: np.info
!python -c "import numpy; numpy.info(numpy.add)"
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [53]:
hint(7)
#!python -c "import numpy; numpy.info(numpy.arange)"
#arange[10,50,step=1)
A = np.arange(10,50,step=1)
print(A)
answer(7)


hint: arange
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [55]:
hint(8)
#A = A[39::-1]
A = A[::-1]
print(A)
answer(8)

hint: array[::-1]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [63]:
hint(9)
#!python -c "import numpy; numpy.info(numpy.reshape)"
A = np.arange(0,9)
A = np.reshape(A,(3,3))
print(A)

hint: reshape
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [68]:
hint(10)
A = [1,2,0,0,4,0]
idx = np.nonzero(A)
print(idx)

hint: np.nonzero
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [71]:
hint(11)
A = np.eye(3)
print(A)

hint: np.eye
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [73]:
hint(12)
A = np.random.random((3,3,3))
print(A)

hint: np.random.random
[[[0.26396426 0.10498241 0.94331941]
  [0.87916474 0.39593574 0.1396696 ]
  [0.67707078 0.62045623 0.56256796]]

 [[0.30074932 0.15247964 0.27387446]
  [0.93270099 0.41163157 0.07188962]
  [0.27886906 0.0841583  0.76523522]]

 [[0.01818033 0.84655566 0.99133839]
  [0.90666253 0.57084333 0.8390781 ]
  [0.32956675 0.40386034 0.04579355]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [76]:
A = np.random.random((10,10))
print(A,A.max(),A.min())
answer(13)

[[0.27709702 0.18413723 0.88459055 0.14702985 0.6758978  0.63347098
  0.71574527 0.45570527 0.74773722 0.28000192]
 [0.4833616  0.58654047 0.06152592 0.52871182 0.0115627  0.80466037
  0.54736939 0.51540144 0.09932957 0.87388053]
 [0.92703891 0.18584737 0.12844859 0.5402069  0.28870406 0.21878366
  0.54991154 0.67826666 0.74975456 0.33739149]
 [0.20474567 0.0653002  0.05954306 0.11488892 0.52774075 0.14600463
  0.98705106 0.82855294 0.68846964 0.63585599]
 [0.97083723 0.20133593 0.2843437  0.08101986 0.88751812 0.10176266
  0.77829246 0.47642186 0.24078341 0.53358132]
 [0.30837333 0.12547875 0.8799727  0.52177597 0.91188473 0.46171894
  0.05733917 0.08762049 0.24786346 0.3099079 ]
 [0.10112919 0.06911944 0.92804319 0.31256485 0.82570495 0.53188652
  0.70296012 0.96866251 0.91551994 0.68276355]
 [0.4729969  0.04905714 0.85682466 0.43767045 0.20315768 0.77988263
  0.62795298 0.14762261 0.59480508 0.98056186]
 [0.74253262 0.3976908  0.51790919 0.95011438 0.43566857 0.21168613
  0.54033896

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [81]:
A = np.random.random(30)
print(A.mean())
answer(14)

0.5515193311805248
Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [92]:
hint(15)
A = np.ones(25)
A = np.reshape(A,(5,5))
print(A)
A[1:-1,1:-1] = 0
print(A)

hint: array[1:-1, 1:-1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [114]:
hint(16)
#!python -c "import numpy; numpy.info(numpy.pad)"
A = np.random.random((2,2))
A = np.pad(A,(1,1),mode='constant')
print(A)
answer(16)

hint: np.pad
[[0.         0.         0.         0.        ]
 [0.         0.01670372 0.80600882 0.        ]
 [0.         0.65295358 0.39928507 0.        ]
 [0.         0.         0.         0.        ]]
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Not a solution to this problem but good to know: using fancy indexing for in-place edit
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [117]:
print(0*np.nan) #nan
print(np.nan == np.nan) #false
print(np.inf > np.nan) #false 
print(np.nan - np.nan) #nan
print(np.nan in set([np.nan])) #True
print(0.3 == 3*0.1) # false
answer(17)

nan
False
False
nan
True
False
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [129]:
d = [1,2,3,4]
a = np.diag(d,-1)
print(a)
answer(18)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
Z = np.diag(1+np.arange(4),k=-1)
print(Z)
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [139]:
a = np.ones((8,8))
#print(a)
hint(19)
a[::2,::2] = 0
a[1::2,1::2] = 0
print(a)
answer(19)

hint: array[::2]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [149]:
hint(20)
#!python -c "import numpy; numpy.info(numpy.unravel_index)"
x = np.unravel_index(99,(6,7,8))
print(x)
answer(20)

hint: np.unravel_index
(1, 5, 3)
print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
#!python -c "import numpy; numpy.info(numpy.tile)"
a = np.tile([[1,0],[0,1]],(4,4))
print(a)
answer(21)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [163]:
hint(22)
a = np.random.random((5,3))
print(a)
a = (a - a.mean())/a.std()
print(a)
answer(22)

hint: (x -mean)/std
[[0.74362074 0.79813167 0.56321706]
 [0.653875   0.74804096 0.32325363]
 [0.52205141 0.59718758 0.73200463]
 [0.01551488 0.87801889 0.51853216]
 [0.51508029 0.48576529 0.22205975]]
[[ 0.84972109  1.09454023  0.03949317]
 [ 0.44665554  0.86957314 -1.03822918]
 [-0.14538977  0.19206137  0.79755088]
 [-2.42034358  1.45332923 -0.1611954 ]
 [-0.17669842 -0.30835776 -1.49271053]]
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [161]:
hint(23)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
answer(23)

hint: np.dtype
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [162]:
a = np.ones((5,3))
b = np.ones((3,2))
print(a@b)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [173]:
a = np.arange(20)
print(a)
a[(3<a)&(a<8)] *= -1
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [3]:
#!python -c "import numpy; numpy.info(numpy.sum)"
print(sum(range(5),-2))
from numpy import *
print(sum(range(5),-1))

8
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [8]:
answer(27)
Z = np.ones(5)
Z**Z
Z <- Z
1j*Z
Z/1/1

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


array([1., 1., 1., 1., 1.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [12]:
answer(28)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
print(8//3)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
nan
0
[-2.14748365e+09]
2


C:\Users\Hp\AppData\Local\Temp\ipykernel_14924\969225271.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Hp\AppData\Local\Temp\ipykernel_14924\969225271.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Hp\AppData\Local\Temp\ipykernel_14924\969225271.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [18]:

answer(29)
Z = np.random.uniform(-10,+10,10)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
[-3.  7.  2.  2.  4. -3. -3. -8. -4. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [14]:
hint(30)
a = [1,2,3,4,5]
b = [4,5,6,7,8]
c = np.intersect1d(a,b)
print(c)

hint: np.intersect1d
[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain at least one element of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)